<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GridViewFive.aspx.cs" Inherits="GridViewFive" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <h1>Inserting Rows Via a DetailsView</h1>
    <form id="form1" runat="server">
    <div>
        <asp:ObjectDataSource ID="myObjectDataSource"
                              TypeName="DataBinding.CompanyThree"
                              DataObjectTypeName="DataBinding.Employee"
                              EnablePaging="true"
                              SelectMethod="GetEmployees"
                              StartRowIndexParameterName="startIndex"
                              MaximumRowsParameterName="maximum"
                              SelectCountMethod="GetEmployeeCount"
                              InsertMethod="AddEmployee"
                              UpdateMethod="UpdateEmployee"
                              DeleteMethod="DeleteEmployee"
                              runat="server">
        </asp:ObjectDataSource>
    
    </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" 
                      BackColor="White" BorderColor="#3366CC"
                      BorderStyle="None" BorderWidth="1px" 
                      CellPadding="4" DataSourceID="myObjectDataSource"
                      AllowPaging="true" PageSize="3"
                      AutoGenerateEditButton="true" 
                      AutoGenerateDeleteButton="true"
                      DataKeyNames="ID">
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <RowStyle BackColor="White" ForeColor="#003399" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <Columns>
                <asp:BoundField  DataField="ID" ReadOnly="true" HeaderText="Employees ID" />
                <asp:BoundField  DataField="Name" HeaderText="Employees Name" />
                <asp:BoundField  DataField="Department" HeaderText="Employees Department" />
                <asp:BoundField  DataField="Salary" HeaderText="Employees Salary" />
            </Columns>
        </asp:GridView>
        <h2>Insert a New Employee Below...</h2>
        <asp:DetailsView DataKeyNames="ID"
                         DataSourceID="myObjectDataSource"
                         DefaultMode="Insert"
                         AutoGenerateRows="false"
                         runat="server">
            <Fields>
                <asp:BoundField  DataField="ID" ReadOnly="true" HeaderText="Employees ID" />
                <asp:BoundField  DataField="Name" HeaderText="Employees Name" />
                <asp:BoundField  DataField="Department" HeaderText="Employees Department" />
                <asp:BoundField  DataField="Salary" HeaderText="Employees Salary" />
                <asp:CommandField ShowInsertButton="true" />
            </Fields>
        </asp:DetailsView>
    </form>
</body>
</html>
